/* VO-AI | config.js — generated by tools/make-config.js; do not edit by hand.
   Public values only (project URL + anon key), protected by row-level security.
   Empty = offline only: the app keeps all data in this browser. */
var VOAI_CONFIG = {
    "supabaseUrl": "https://iydepesvotaghiuztmed.supabase.co",
    "supabaseAnonKey": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZGVwZXN2b3RhZ2hpdXp0bWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTExOTkxMDcsImV4cCI6MjEwNjc3NTEwN30.gZG_HTqVNHSyyN08t6L260Sy9LbYdw271r5j9H69NSQ"
};
