/* Writes js/config.js from the environment, so the browser learns which
   Supabase project to use (js/cloud.js). Only the two values that are
   public by design go in: the project URL and the anon key. Every row is
   protected by row-level security (supabase/migrations). Never put the
   service-role key or any API key here.

     SUPABASE_URL=… SUPABASE_ANON_KEY=… node tools/make-config.js
     node tools/make-config.js --off     (offline-only build: no cloud)
*/
const fs = require("fs");
const path = require("path");

const off = process.argv.includes("--off");
const url = off ? "" : (process.env.SUPABASE_URL || "").trim().replace(/\/+$/, "");
const key = off ? "" : (process.env.SUPABASE_ANON_KEY || "").trim();

if (!off && (!url || !key)) {
    console.error("Set SUPABASE_URL and SUPABASE_ANON_KEY, or pass --off.");
    process.exit(1);
}
if (!off && !/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(url)) {
    console.error("SUPABASE_URL does not look like https://<project>.supabase.co");
    process.exit(1);
}
/* A service-role key is a JWT whose payload says role "service_role";
   refuse to publish one by mistake. */
if (key) {
    let role = "";
    try { role = JSON.parse(Buffer.from(key.split(".")[1], "base64url").toString()).role || ""; } catch (e) { /* new-style key */ }
    if (role === "service_role" || /^sb_secret_/.test(key)) {
        console.error("That is a secret (service-role) key. Use the anon / publishable key.");
        process.exit(1);
    }
}

const body =
    "/* VO-AI | config.js — generated by tools/make-config.js; do not edit by hand.\n" +
    "   Public values only (project URL + anon key), protected by row-level security.\n" +
    "   Empty = offline only: the app keeps all data in this browser. */\n" +
    "var VOAI_CONFIG = " + JSON.stringify({ supabaseUrl: url, supabaseAnonKey: key }, null, 4) + ";\n";
fs.writeFileSync(path.join(__dirname, "..", "js", "config.js"), body);
console.log(off ? "js/config.js: offline only" : "js/config.js: cloud enabled for " + url);
